package practica;
// Generated 13-ene-2020 20:00:48 by Hibernate Tools 5.4.7.Final

/**
 * Personajes generated by hbm2java
 */
public class Personajes implements java.io.Serializable {

	private int personajeId;
	private Faccion faccion;
	private String nombrePersonaje;
	private Integer ataque;
	private Integer defensa;

	public Personajes() {
	}

	public Personajes(int personajeId) {
		this.personajeId = personajeId;
	}

	public Personajes(int personajeId, Faccion faccion, String nombrePersonaje, Integer ataque, Integer defensa) {
		this.personajeId = personajeId;
		this.faccion = faccion;
		this.nombrePersonaje = nombrePersonaje;
		this.ataque = ataque;
		this.defensa = defensa;
	}

	public int getPersonajeId() {
		return this.personajeId;
	}

	public void setPersonajeId(int personajeId) {
		this.personajeId = personajeId;
	}

	public Faccion getFaccion() {
		return this.faccion;
	}

	public void setFaccion(Faccion faccion) {
		this.faccion = faccion;
	}

	public String getNombrePersonaje() {
		return this.nombrePersonaje;
	}

	public void setNombrePersonaje(String nombrePersonaje) {
		this.nombrePersonaje = nombrePersonaje;
	}

	public Integer getAtaque() {
		return this.ataque;
	}

	public void setAtaque(Integer ataque) {
		this.ataque = ataque;
	}

	public Integer getDefensa() {
		return this.defensa;
	}

	public void setDefensa(Integer defensa) {
		this.defensa = defensa;
	}

}
